### ISSUE TITLE
Running evault project

### ISSUE THREAD

**Issue by pettamrakesh3** [rohitroy-github/vite-project-evault#42]
hii bro..

Brother, I am getting the error while running the sih-evault-project. I am unable to sign up for the main page. All is set up, and adding the alchemy key mentioned in the .env.example is done. I am still unable to sign up for the main page. Can you please provide any references to completely run this project? It will help us a lot.

Thank you..

**Comment by rohitroy-github** [comment]
Hey @pettamrakesh3, please refer to the updated readMe file for running the project. #

I would appreciate it if you put a ⭐ to my project. If you face any further issue, feel free to post it under the issues tab.
