### ISSUE TITLE
unable to fetch cases

### ISSUE THREAD

**Issue by Ir0nSide** [rohitroy-github/vite-project-evault#47]
![Screenshot (30)](https://github.com/rohitroy-github/vite-project-evault/assets/114598045/6948ac57-340e-4373-b2c6-9f7642e11b70)
i am not able to fetch any kind of data as well as i am unable to get the cases login as a lawyer sign in or login

**Comment by rohitroy-github** [comment]
I had a meet with you right now. Is your issue solved @Ir0nSide ?
